### ISSUE TITLE
Add navigation pane

### ISSUE THREAD

**Issue by louissegal** [louissegal/louissegal.github.io#2]
Add a right to left nav pane?

**Comment by jimijameson** [comment]
![sidepanel](https://cloud.githubusercontent.com/assets/16170257/11681196/4916d50e-9e55-11e5-8b54-bf24361928ed.png)

**Comment by waquidvp** [comment]
![image](https://cloud.githubusercontent.com/assets/15846228/11682817/12e913ac-9e5f-11e5-838c-59574dba9a9d.jpeg)

**Comment by waquidvp** [comment]
Something like that

**Comment by louissegal** [comment]
I didn't even realise I posted that from Jimi's account but yes, I'm having a good think.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Dec 9, 2015 at 2:25 AM -0800, "waquidvp" <notifications@github.com<mailto:notifications@github.com>> wrote:


Something like that

-
Reply to this email directly or view it on GitHub<https://github.com/louissegal/louissegal.github.io/issues/2#issuecomment-163179795>.

________________________________
This electronic message transmission contains information that is deemed confidential or privileged by the sender. The information is intended to be for the use of the individual or entity named as recipient(s) above, only. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited. If you have received this electronic transmission in error, please notify us immediately by replying to the email or by telephoning University Technical College Cambridge on 01223 724300. Once you have done this please delete the email/attachment and do not disclose, copy, distribute, or rely on it. Please note that any opinions presented in this email are solely those of the author and do not necessarily represent those of University Technical College Cambridge. No employee or agent is authorised to conclude any binding agreement on behalf of University Technical College Cambridge with another party by email without express written confirmation by the Principal. Under the Data Protection Act 1998 and the Freedom of Information Act 2000 the contents of emails and their attachments (sent to or received) may need to be disclosed. The UTC reserves the right to monitor both sent and received emails. WARNING: Although University Technical College Cambridge has taken reasonable precautions to ensure no viruses are present in this email, the College cannot accept responsibility for any loss or damage arising from the use of this email or attachments.
________________________________
UTC Cambridge <http://utccambridge.co.uk>
